### ISSUE TITLE
[Bug]: Regression on blank configuration for indentation

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-various-textobjs#115]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.

### Bug Description

It looks like in a recent commit you've changed the behaviour for indent so that it only accepts the blanks/noblanks parameter by global configuration rather than a parameter on the function call. Unfortunately this seems to mean I can no longer map different key bindings to both include and exclude blanks, which is what I'd been doing up till now:

https://github.com/andrewferrier/dotfiles/blob/3dd41c3b40d9255dc3a8e0f4f02870a174450e7b/stow/if-command/nvim/.config/nvim/lua/plugin-specs/nvim-various-textobjs.lua#L13

I wonder if you might consider continuing to support the function parameters as an advanced/additional optional option? It could override the global setup() value if passed.

### Reproduction & sample text

x

### neovim version

```Text
NVIM v0.11.0-dev-1325+g30726c778c
```

**Comment by chrisgrieser** [comment]
Well, technically it's not a bug or a regression, but simply a breaking change.

Though I can see the problem, I simply haven't expected that there are people who use both variants. I thought that it was simply a question of preference for one or the other, making it better suited for a config option. 

However, a solution to your problem would be to simply call `setup()` before every call of the text object:

```lua
vim.keymap.set("o", "ii", function()
	require("various-textobjs").setup {
		textobjs = { indentation = { blanksAreDelimiter = true } },
	}
	return "<cmd>lua require('various-textobjs').indentation('inner', 'inner')<CR>"
end, { expr = true, desc = "indentation without blanks" })

vim.keymap.set("o", "ii", function()
	require("various-textobjs").setup {
		textobjs = { indentation = { blanksAreDelimiter = false } },
	}
	return "<cmd>lua require('various-textobjs').indentation('inner', 'inner')<CR>"
end, { expr = true, desc = "indentation with blanks" })
```

In fact, things like this are the very reason why I made it that in most of my plugins, `setup` can be called multiple times. It wasn't the case for various-textobjs, since I didn't think there would ever be the need, but I enabled being able to call `setup` multiple times, so that you can use the mappings above to solve your issue.

In case there is a higher demand to have both variants available, I'll think of a better solution, but if not, this method should probably be enough.
