### ISSUE TITLE
Feature Request: anti-text object to iS/aS

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-various-textobjs#4]
### Feature Requested

As described in https://github.com/chrisgrieser/nvim-various-textobjs/issues/3, I think that iS / aS are described the wrong way round. However, I would really love text objects that operate that way - meaning they are greedy at consuming `-`, which `iw` currently is not. I would love a text object for a word that consider that as part of the word. Would you consider adding this?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
actually, you can do that without a plugin, using the `iskeyword` option (which essentially defines which characters are considered part of a word, i.e. non-word-delimiters)

What I do is to add `.` and `-` to `iskeyword` in general, and then use iW for the big word, iw for a word (including `.` and `-`) and then subword for something only consisting of letters.

Will add info on `iskeyword` to the docs though, since not everyone is familiar with it :)

**Comment by andrewferrier** [comment]
I actually am familiar with `iskeyword`. The challenge is that I don't like to change it; sometimes its default behavior is useful, but then I also want the whole word in other circumstances, *without* what I've set in `iskeyword`. Understand if you don't want to support that though, I get there might be too much feature creep going on here..

**Comment by andrewferrier** [comment]
Fair enough, and yes good tip thanks - I'll do that!
