### ISSUE TITLE
[Bug]: toNextClosingBracket does not work correctly

### ISSUE THREAD

**Issue by kevintraver** [chrisgrieser/nvim-various-textobjs#41]
### Bug Description

`toNextClosingBracket` is not working in the latest version.

Tested on a clean configuration using lazy.nvim and default setup

### Reproduction & Sample Text

example: 

`("Hello World")`

cursor is on **_W_**, and then type `c%`

result: 

`orld ")`

expected:

`("Hello `

### neovim version

```Text
NVIM v0.10.0-dev
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by kevintraver** [comment]
I also tested on `NVIM v0.9.1`

**Comment by chrisgrieser** [comment]
Ah, that actually happens not due to a bug, but as the keymap set by
`nvim-various-textobjects` is overridden by vim's built-in keymap. Normally,
plugins, vim's built-in keymaps do not override plugin keymaps, apparently,
`omap %` is technically not set by vim itself, but by a plugin (matchit) which
is by default shipped with vim. And that seems to cause a race condition, where
`various-textobjects` seems to be quicker, probably due to `lazy.nvim` being a
little bit too fast. 😛

**Comment by kevintraver** [comment]
Thanks for looking into this and the explanation!
