### ISSUE TITLE
Change Textobj: Subword outer textobj includes the preceding delimiter when it's the last word.

### ISSUE THREAD

**Issue by singlexyz** [chrisgrieser/nvim-various-textobjs#83]
### Change requested

When selecting the last word, the Subword outer text object includes the preceding delimiter.

### Sample Text

```
111-222-333
```
When cursor on `111`, subword outer is `111-`
When cursor on `222`, subword outer is `222-`

When cursor on `333`, subword outer and inner both are `333`. 
In this case, `-333` for subword outer would be more in line with expectations.

In other words, subword outer only includes the following delimiter, but when it's the last subword, subword outer switches to include the preceding delimiter.

### Checklist

- [X] The textobj would be useful to more users than just me. ([You can use the API to create custom textobj.](../#advanced-usage--api))
- [X] This is a feature request to change an existing textobject, not a bug report. (Use the bug report form for those.)

**Comment by mawkler** [comment]
Also, when removing the first subword in a camelCased word with `daS` I would expect the remaining word to still be camelCased. However, currently the word becomes PascalCased:

### Current behaviour (with cursor at `^`):

```
fooBarBaz
 ^
```

After pressing `daS`:

```
BarBaz
```

### Expected behaviour (with cursor at `^`):

```
fooBarBaz
 ^
```

After pressing `daS`:

```
barBaz
```

Note that would still expect `iS` to _not_ alter the case of the preceding word. That way if I wanted to just `c`hange the first subword, I could use `ciS` and get `BarBaz` (not `barBaz`).

This is also how [vim-textobj-variable-segment](https://github.com/Julian/vim-textobj-variable-segment) works. Do you also agree with this behaviour?

**Comment by chrisgrieser** [comment]
@mawkler That's a very different request, I thus created a separate issue for it #113

**Comment by chrisgrieser** [comment]
fixed
