### ISSUE TITLE
[Bug]: anyQuote iq doesn't look forwards for quotes and get the pair, gets mixed up with previous quote on line

### ISSUE THREAD

**Issue by Ajaymamtora** [chrisgrieser/nvim-various-textobjs#98]
### Bug Description
Given this text
```lua     
     require("utils.search_utils").[x]grug_search({path}, nil, "vnew", "", is_single)
```

If I do `yiq` where the x is, the text between the quote after ".search_utils" and "vnew" is yanked.

if I do `yi"` it yanks the text "vnew" which is what I'd expect because it's looked forwards for the quote and found the pair

### Relevant Screenshot

`yiq` behaviour (red underline is whats yanked):

<img width="784" alt="Screenshot 2024-08-02 at 15 51 06" src="https://github.com/user-attachments/assets/2e2ba618-0295-4b8c-bdf2-3a720943733d">

expected behaviour with `yi"` (red underline is whats yanked):
<img width="639" alt="Screenshot 2024-08-02 at 15 52 38" src="https://github.com/user-attachments/assets/fba3d665-262c-44b3-9424-3bbbbec1381d">

### Reproduction & Sample Text

See above

### neovim version

```Text
0.10 stable
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
That behavior is on purpose, `anyQuote` is purposefully "dumb", because that is also how the builtin vim `i"` works. I can see that this is annoying, but I with this plugin, I generally try to be consistent with the builtin vim behavior.

And in fact, `yi"` and `yiq` both yank the same `).[x]grug_search({path}, nil, ` for me in your example. So assume you have some other plugin that changes the `i"` behavior?

Also, to properly evaluate which quotes designate a "true" string, you'd probably need something like a treesitter parser. Maybe create a FR at `nvim-treesitter-textobjs`?
